version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-telco
    environment:
      - ORACLE_PASSWORD=mysecretpassword
    ports:
      - "1521:1521"
    volumes:
      - ./TABLE_CREATION_SCRIPTS.sql:/container-entrypoint-initdb.d/TABLE_CREATION_SCRIPTS.sql
